name: Compilation
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: src/
          compiler: lualatex
          args: -file-line-error -interaction=nonstopmode -output-format=pdf
      - uses: dante-ev/latex-action@latest
        with:
          root_file: main.aux
          working_directory: src/
          compiler: bibtex
          args: ''
      - uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: src/
          compiler: lualatex
          args: -file-line-error -interaction=nonstopmode -output-format=pdf
      - uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: src/
          compiler: lualatex
          args: -file-line-error -interaction=nonstopmode -output-format=pdf
      - name: Get commit hash and rename PDF
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          mv src/main.pdf "src/${{ env.branch }}-${{ env.sha_short }}.pdf"
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ env.branch }}-${{ env.sha_short }}.pdf"
          path: "src/${{ env.branch }}-${{ env.sha_short }}.pdf"
