name: TeXtidote
on: push
jobs:
  TeXtidote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ChiefGokhlayeh/textidote-action@v5
        id: textidote
        with:
          root_file: src/main.tex
          args: --check en --dict src/whitelist.txt --ignore sh:seclen,lt:en:UPPERCASE_SENTENCE_START
      - name: Fail
        if: ${{ steps.textidote.outputs.num_warnings != 0 }}
        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
